import { Footer } from "../footer/footer";
import { Header } from "../header/header";
import { Menu } from "../menu/menu";
import Head from "next/head";

export interface menuItemsI {
  path: string;
  label: string;
}

export function Layout({ children }: any) {
  const menuItems: Array<menuItemsI> = [
    { path: "/", label: "Inicio" },
    { path: "/about", label: "Nosotros" },
  ];

  return (
    <>
      <Head>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header>
        <Menu menuItems={menuItems}></Menu>
      </Header>
      <main>{children}</main>
      <Footer></Footer>
    </>
  );
}
